### PR TITLE
a way to circumvent limitation on custom enum implementations when using string().enumurated() 

### LINKED ISSUE #11: fix: string.enumerated fails if trying to validate against a custom enum.name getter
**What happened**

validation fails when it should succeed

**Code**

```dart
void main() {
print(string().enumerated(EndpointMethods.values).parse("GET").success);
}

enum EndpointMethods {
  get,
  post,
  put,
  delete;

  String get name => switch (this) {
    EndpointMethods.get => "GET",
    EndpointMethods.post => "POST",
    EndpointMethods.put => "PUT",
    EndpointMethods.delete => "DELETE",
  };
}

```

**What should have happened**
it should print `true`

**What actually happens**
it prints `false`

**------------------**

it weird because i checked the implementation and i saw it definitely compares against `<T>.name`.
why does it even have to be an enum !!!! just make it a list of String.

### PR DESCRIPTION
**Pull request by Hanibachi**
# Description

give dev option to specifiy a transformer callback on enumValue.name before it is used to validate a string value against a list of enums.

Fixes #11 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Summary by CodeRabbit

- **New Features**
  - Added support for transforming enum names during string validation, allowing custom comparison logic when checking if a string matches an enum value.

- **Documentation**
  - Expanded documentation to explain the new parameter for transforming enum names during validation.

### CODE REVIEW

**Comment by Hanibachi** [comment]
i guess it'd still be cool to add a separate `contained(List<String> values)` method to reduce boiler plate enum declarations in some cases.

File: lib/src/validators/string.dart [hunk 1]
```diff
@@ -388,11 +388,13 @@ class PatternHexColorStringChecks extends AcanthisCheck<String> {
...
 class EnumeratedStringCheck<T extends Enum> extends AcanthisCheck<String> {
   final List<T> enumValues;
+  final String Function(String name)? nameTransformer;
 
   EnumeratedStringCheck(
       {required this.enumValues,
+      this.nameTransformer,
       String? message,
-      String Function(List<T> enumValues)? messageBuilder})
+      String Function(List<Enum> enumValues)? messageBuilder})
```
Comment (francescovallone) [inline lib/src/validators/string.dart:397]: Why is it Enum here? The generic provides the correct flexibility.

Comment (Hanibachi) [reply lib/src/validators/string.dart:397]: artifact from when i was testing a different approach

File: lib/src/validators/string.dart [hunk 2]
```diff
@@ -401,8 +403,12 @@ class EnumeratedStringCheck<T extends Enum> extends AcanthisCheck<String> {
 
   @override
   bool call(String value) {
-    final enumValue = enumValues.map((e) => e.name).toList();
-    return enumValue.contains(value);
+    return enumValues.any((enumV) =>
+        value ==
+        switch (nameTransformer != null) {
```
[the remark this answers is not in the document]
Comment (Hanibachi) [reply lib/src/validators/string.dart:408]: there was i reason why i didn't go with that .. but now i forgot ! i'll change it anyways
